# docker-compose run --rm npm init
version: '3.8'

services:
  npm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${UID}
        - GROUP_ID=${GID}
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
